name: Test info

on:
  workflow_dispatch:

jobs:

  info:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npx cypress info
      - run: npx cypress version
      - run: node -v

  info-debug:
    runs-on: ubuntu-24.04
    env:
      DEBUG:  'cypress:*'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npx cypress info
